### ISSUE TITLE
Add a way to get sha1 digest

### ISSUE THREAD

**Issue by lejara** [lejara/easy-python-file-utils#3]
For example, given a path like "/home/kim/mydata.txt", which contains the text The quick brown fox jumps over the lazy dog, return 2fd4e1c67a2d28fced849ee1bb76e7391b93eb12

**Comment by GeoZac** [comment]
Can I?
The solution is pretty simple as hashlib already has support for almost all standards

**Comment by lejara** [comment]
Sure! Go for it!

**Comment by lejara** [comment]
Just make another python file with that function in it
